config/routes.rb
Hospital::Application.routes.draw do
  
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact_us'
  get 'static_pages/careers'
  get 'static_pages/visiting'
  get 'static_pages/services'
  
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions
  
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "static_pages#home" # remove ./public/index.html
  resources :users
  
  resources :discharges

  resources :bills

  resources :logins

  resources :doctors

  resources :appointments
  
  resources :doctors do
      resources :appointments
  end
  resources :patients do
     resources :appointments
  end

end

app/models/discharge.rb
class Discharge < ActiveRecord::Base
    belongs_to :patient
    belongs_to :login
    has_one :bill, dependent: :destroy
end

app/controllers/discharges_controller.rb
class DischargesController < ApplicationController
  before_action :set_discharge, only: [:show, :edit, :update, :destroy]

  # GET /discharges
  # GET /discharges.json
  def index
    @discharges = Discharge.all
  end

  # GET /discharges/1
  # GET /discharges/1.json
  def show
  end

  # GET /discharges/new
  def new
    @discharge = Discharge.new
  end

  # GET /discharges/1/edit
  def edit
  end

  # POST /discharges
  # POST /discharges.json
  def create
    @discharge = Discharge.new(discharge_params)

    respond_to do |format|
      if @discharge.save
        format.html { redirect_to @discharge, notice: 'Discharge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @discharge }
      else
        format.html { render action: 'new' }
        format.json { render json: @discharge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discharges/1
  # PATCH/PUT /discharges/1.json
  def update
    respond_to do |format|
      if @discharge.update(discharge_params)
        format.html { redirect_to @discharge, notice: 'Discharge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @discharge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discharges/1
  # DELETE /discharges/1.json
  def destroy
    @discharge.destroy
    respond_to do |format|
      format.html { redirect_to discharges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discharge
      @discharge = Discharge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discharge_params
      params.require(:discharge).permit(:discharge_id, :room_id, :admission_date, :discharge_date, :username, :patient_id)
    end
end

app/helpers/discharges_helper.rb
module DischargesHelper
end

app/views/discharges/_form.html.erb
<%= form_for(@discharge) do |f| %>
  <% if @discharge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discharge.errors.count, "error") %> prohibited this discharge from being saved:</h2>

      <ul>
      <% @discharge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :discharge_id %><br>
    <%= f.number_field :discharge_id %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.number_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :admission_date %><br>
    <%= f.date_select :admission_date %>
  </div>
  <div class="field">
    <%= f.label :discharge_date %><br>
    <%= f.date_select :discharge_date %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.number_field :patient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discharges/edit.html.erb
<h1>Editing discharge</h1>

<%= render 'form' %>

<%= link_to 'Show', @discharge %> |
<%= link_to 'Back', discharges_path %>

app/views/discharges/index.html.erb
<h1>Listing discharges</h1>

<table>
  <thead>
    <tr>
      <th>Discharge</th>
      <th>Room</th>
      <th>Admission date</th>
      <th>Discharge date</th>
      <th>Username</th>
      <th>Patient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <FORM>
<div style=" position:relative; left:80px; top:450px;" >
<input type="button" value="HOME" ONCLICK="window.location.href='http://localhost:3000/'"><br><br> 
<style>
input[type="button"]{
/* change these properties to whatever you want */
background-color: #F8F8FF;
width: 15%;
color: #1E90FF;	
font-weight: bold;
border-radius: 10px;
font-size:15pt;
position: relative;
left: 950px;
top: -500px;
min-width:65px;min-height:65px;
}
</style>
</div>
</FORM>
    <% @discharges.each do |discharge| %>
      <tr>
        <td><%= discharge.discharge_id %></td>
        <td><%= discharge.room_id %></td>
        <td><%= discharge.admission_date %></td>
        <td><%= discharge.discharge_date %></td>
        <td><%= discharge.username %></td>
        <td><%= discharge.patient_id %></td>
        <td><%= link_to 'Show', discharge %></td>
        <td><%= link_to 'Edit', edit_discharge_path(discharge) %></td>
        <td><%= link_to 'Destroy', discharge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discharge', new_discharge_path %>

app/views/discharges/new.html.erb
<h1>New discharge</h1>

<%= render 'form' %>

<%= link_to 'Back', discharges_path %>

app/views/discharges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discharge:</strong>
  <%= @discharge.discharge_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @discharge.room_id %>
</p>

<p>
  <strong>Admission date:</strong>
  <%= @discharge.admission_date %>
</p>

<p>
  <strong>Discharge date:</strong>
  <%= @discharge.discharge_date %>
</p>

<p>
  <strong>Username:</strong>
  <%= @discharge.username %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @discharge.patient_id %>
</p>

<%= link_to 'Edit', edit_discharge_path(@discharge) %> |
<%= link_to 'Back', discharges_path %>