config/routes.rb
Hospital::Application.routes.draw do
  
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact_us'
  get 'static_pages/careers'
  get 'static_pages/visiting'
  get 'static_pages/services'
  
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions
  
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "static_pages#home" # remove ./public/index.html
  resources :users
  
  resources :discharges

  resources :bills

  resources :logins

  resources :doctors

  resources :appointments
  
  resources :doctors do
      resources :appointments
  end
  resources :patients do
     resources :appointments
  end

end

app/models/bill.rb
class Bill < ActiveRecord::Base
    belongs_to :login
    belongs_to :appointment
    belongs_to :discharge
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:bill_id, :bill_amount, :payment_mode, :discharge_id, :appt_id, :username)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bill_id %><br>
    <%= f.number_field :bill_id %>
  </div>
  <div class="field">
    <%= f.label :bill_amount %><br>
    <%= f.number_field :bill_amount %>
  </div>
  <div class="field">
    <%= f.label :payment_mode %><br>
   <%= f.select(:payment_mode, options_for_select([['cash', 'cash'], ['card', 'card']])) %>
  </div>
  </div>
  <div class="field">
    <%= f.label :discharge_id %><br>
    <%= f.number_field :discharge_id %>
  </div>
  <div class="field">
    <%= f.label :appt_id %><br>
    <%= f.number_field :appt_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <thead>
    <tr>
      <th>Bill</th>
      <th>Bill amount</th>
      <th>Payment mode</th>
      <th>Discharge</th>
      <th>Appt</th>
      <th>Username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <FORM>
<div style=" position:relative; left:80px; top:450px;" >
<input type="button" value="HOME" ONCLICK="window.location.href='http://localhost:3000/'"><br><br> 
<style>
input[type="button"]{
/* change these properties to whatever you want */
background-color: #F8F8FF;
width: 15%;
color: #1E90FF;	
font-weight: bold;
border-radius: 10px;
font-size:15pt;
position: relative;
left: 950px;
top: -500px;
min-width:65px;min-height:65px;
}
</style>
</div>
</FORM>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.bill_id %></td>
        <td><%= bill.bill_amount %></td>
        <td><%= bill.payment_mode %></td>
        <td><%= bill.discharge_id %></td>
        <td><%= bill.appt_id %></td>
        <td><%= bill.username %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bill:</strong>
  <%= @bill.bill_id %>
</p>

<p>
  <strong>Bill amount:</strong>
  <%= @bill.bill_amount %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @bill.payment_mode %>
</p>

<p>
  <strong>Discharge:</strong>
  <%= @bill.discharge_id %>
</p>

<p>
  <strong>Appt:</strong>
  <%= @bill.appt_id %>
</p>

<p>
  <strong>Username:</strong>
  <%= @bill.username %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>