config/routes.rb
Hospital::Application.routes.draw do
  
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact_us'
  get 'static_pages/careers'
  get 'static_pages/visiting'
  get 'static_pages/services'
  
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions
  
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "static_pages#home" # remove ./public/index.html
  resources :users
  
  resources :discharges

  resources :bills

  resources :logins

  resources :doctors

  resources :appointments
  
  resources :doctors do
      resources :appointments
  end
  resources :patients do
     resources :appointments
  end

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
    has_many :appointments, dependent: :destroy
    has_many :patients, dependent: :destroy
    belongs_to :login

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doctor }
      else
        format.html { render action: 'new' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:doc_id, :doc_name, :designation, :address, :doc_contact_num, :fee, :username)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doc_id %><br>
    <%= f.number_field :doc_id %>
  </div>
  <div class="field">
    <%= f.label :doc_name %><br>
    <%= f.text_field :doc_name %>
  </div>
  <div class="field">
    <%= f.label :designation %><br>
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :doc_contact_num %><br>
    <%= f.text_field :doc_contact_num %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.number_field :fee %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <thead>
    <tr>
      <th>Doc</th>
      <th>Doc name</th>
      <th>Designation</th>
      <th>Address</th>
      <th>Doc contact num</th>
      <th>Fee</th>
      
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <FORM>
<div style=" position:relative; left:80px; top:450px;" >
<input type="button" value="HOME" ONCLICK="window.location.href='http://localhost:3000/'"><br><br> 
<style>
input[type="button"]{
/* change these properties to whatever you want */
background-color: #F8F8FF;
width: 15%;
color: #1E90FF;	
font-weight: bold;
border-radius: 10px;
font-size:15pt;
position: relative;
left: 950px;
top: -500px;
min-width:65px;min-height:65px;
}
</style>
</div>
</FORM>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.doc_id %></td>
        <td><%= doctor.doc_name %></td>
        <td><%= doctor.designation %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.doc_contact_num %></td>
        <td><%= doctor.fee %></td>
        <td><%= link_to 'Show', doctor %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doc:</strong>
  <%= @doctor.doc_id %>
</p>

<p>
  <strong>Doc name:</strong>
  <%= @doctor.doc_name %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @doctor.designation %>
</p>

<p>
  <strong>Address:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>Doc contact num:</strong>
  <%= @doctor.doc_contact_num %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @doctor.fee %>
</p>



<h2>Appointments</h2>
<div id="appointments">
  <%  @doctor.appointments.each do |appointment| %>
  <%= div_for appointment do %>
  <p>
   <%= h(appointment.appt_id) %>
 </p>
<% end %>
<% end %>
</div>


<%= form_for([@doctor, Appointment.new]) do |f| %>
<p> <%= f.label :appt_id, "appt_id" %> <br />
  <%= f.text_area :appt_id %>
  </p>
  <p> <%= f.label :appt_duration, "appt_duration" %> <br />
  <%= f.text_area :appt_duration %>
  </p>
  <p> <%= f.label :appt_date, "appt_date" %> <br />
  <%= f.text_area :appt_date %>
  </p>
  
  <p> <%= f.label :doctor_id, "doctor_id" %> <br />
  <%= f.text_area :doctor_id %>
  </p>
  <p> <%= f.label :patient_id, "patient_id" %> <br />
  <%= f.text_area :patient_id %>
  </p>
  <p> <%= f.submit "Add Appointment" %> </p>
  <% end %>
<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>